plugins {
    id 'java'
    id 'org.springframework.boot' version "$springBootVersion"
    id 'io.spring.dependency-management' version "$ioSpringDependencyManagementVersion"
}

group = 'org.oladushek'
version = '1.0.0'
description = 'module2-5'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(23)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-security'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    implementation("org.springframework.boot:spring-boot-starter-webflux")
    implementation 'org.springframework.session:spring-session-core'

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'com.mysql:mysql-connector-j'

    implementation 'org.flywaydb:flyway-mysql'
    implementation 'org.flywaydb:flyway-core'
    implementation "com.github.spotbugs:spotbugs-annotations:$googleSpotbugsVersion"
    implementation "io.minio:minio:$ioMinioVersion"

    implementation "io.jsonwebtoken:jjwt-api:$jsonWebTokenVersion"
    runtimeOnly "io.jsonwebtoken:jjwt-impl:$jsonWebTokenVersion"
    runtimeOnly "io.jsonwebtoken:jjwt-jackson:$jsonWebTokenVersion"
    implementation "jakarta.xml.bind:jakarta.xml.bind-api:$jaxbApiVersion"
    implementation "org.mapstruct:mapstruct:$mapStructVersion"
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor "org.mapstruct:mapstruct-processor:$mapStructVersion"

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
}

tasks.named('test') {
    useJUnitPlatform()
}
