version: '3.1'

services:
  db:
    image: mysql:9.4.0
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: module22db
      MYSQL_USER: user
      MYSQL_PASSWORD: user